### ISSUE TITLE
Cursor won't fade

### ISSUE THREAD

**Issue by minkses** [YouTube-Enhancer/extension#1092]
**Describe the bug**
Normally, when leaving the mouse idle for a moment, the cursor disappears when on top of the video, alongside the general UI of the player. Currently the cursor just stays there.

**To Reproduce**

1. Go to any video
2. Let it play
3. Hover cursor over video without moving mouse

**Expected behavior**
Cursor disappears

**Desktop:**

- OS: macOS Tahoe (26.1)
- Browser: Firefox 145.0.2
- Version: 1.30.1

**Additional context**
I checked if whether the video was maximized mattered and it seemed not to affect the issue.

Congratulations on the puppies! Obviously no rush and thank you for the hard work! :)

**Comment by VampireChicken12** [comment]
@minkses can you provide me an export of your settings ? I feel like it's possible some setting make be influencing this behavior

**Comment by minkses** [comment]
Of course! Here you go.

[youtube_enhancer_settings_11-30-2025_03-16-47.json](https://github.com/user-attachments/files/23837209/youtube_enhancer_settings_11-30-2025_03-16-47.json)

**Comment by fabcard** [comment]
Same is happening here.
CachyOS - Gnome 49.2
Firefox 145.0.2

[youtube_enhancer_settings_11-30-2025_01-00-32.json](https://github.com/user-attachments/files/23837569/youtube_enhancer_settings_11-30-2025_01-00-32.json)

**Comment by VampireChicken12** [comment]
@minkses @fabcard could you both share a short video showing the issue, as well as how the page behaves with the extension disabled? That will help confirm whether the extension is contributing to the problem. I tested on my end but wasn’t able to reproduce the behavior.

**Comment by minkses** [comment]
Sure thing!

The issue:
https://github.com/user-attachments/assets/7a4a2ca1-7090-4db5-837a-541ab9189da6

With extension disabled:
https://github.com/user-attachments/assets/f0baac66-c83a-42b1-94d7-6a536f49b9b5

**Comment by VampireChicken12** [comment]
Thank you, I'll look into it further when I can. Right now the only thing that is different is I'm testing on windows using Firefox

**Comment by VampireChicken12** [comment]
@minkses @fabcard I've identified a problem with the default to original audio track feature, That could be causing this issue for now disable that feature until this fix is released https://github.com/YouTube-Enhancer/extension/commit/78ffa26494a67ad65e99a67af78eae2391c4fadb

**Comment by minkses** [comment]
hi there!! it's been a while, so i just wanted to say that the cursor issue is still happening for me. not meant to rush or anything, just to put it out there that this report is still relevant :)

- OS: macOS Tahoe (26.5.1)
- Browser: Firefox 152.0.4
- Version: 1.33.0

thank you for all your hard work!!

**Comment by VampireChicken12** [comment]
> hi there!! it's been a while, so i just wanted to say that the cursor issue is still happening for me. not meant to rush or anything, just to put it out there that this report is still relevant :)
> 
> * OS: macOS Tahoe (26.5.1)
> * Browser: Firefox 152.0.4
> * Version: 1.33.0
> 
> thank you for all your hard work!!

Can you provide the latest settings you have applied. I probably won't be able to reproduce this again but I'll try

**Comment by minkses** [comment]
[youtube_enhancer_settings_07-05-2026_21-51-42.json](https://github.com/user-attachments/files/29680159/youtube_enhancer_settings_07-05-2026_21-51-42.json)

i hope this helps, let me know if you need anything else!!

**Comment by VampireChicken12** [comment]
> [youtube_enhancer_settings_07-05-2026_21-51-42.json](https://github.com/user-attachments/files/29680159/youtube_enhancer_settings_07-05-2026_21-51-42.json)
> 
> i hope this helps, let me know if you need anything else!!

Thanks I'll try to look into it.

**Comment by minkses** [comment]
this issue seems to be fixed in the newest version!

**Comment by VampireChicken12** [comment]
> this issue seems to be fixed in the newest version!

Thanks for replying
