### ISSUE TITLE
if set to force playback speed to a different speed the increase speed buttons display the wrong numbers

### ISSUE THREAD

**Issue by slrgt** [YouTube-Enhancer/extension#592]
**Describe the bug**
if set to force playback speed to a different speed the increase speed buttons display the wrong numbers when you first hover over them. For example if you set the default forced speed to 1.5x when you hover over the increase speed button it will still say Increase Speed to 1.25x as if the current speed is 1.00

**To Reproduce**

1. change Force Speed to 1,5
2. hover over the increase speed button

**Expected behavior**
I would expect it to show Increase Speed to 1.75x since that is the speed it will actually change to 

**Screenshots**
![zen_OWBbdoTL5m](https://github.com/user-attachments/assets/66119c3f-c962-4b35-8900-e2a01442ebd8)

**Desktop (please complete the following information):**

- OS: windows
- Browser Firefox

**Comment by VampireChicken12** [comment]
@slrgt I'm pretty sure I fixed that in
a88d29d1c3fdcb81f6b12b6a1cec531f4abb8b88 and a16cd44d86424920ff8446960964087f959735a9

**Comment by VampireChicken12** [comment]
I discovered it and fixed it but never made an issue

**Comment by slrgt** [comment]
Oh im still getting the bug, are those commits for the next update?

**Comment by VampireChicken12** [comment]
yes @slrgt those have yet to be released

**Comment by slrgt** [comment]
Ah, ok. Thanks!

**Comment by VampireChicken12** [comment]
no problem
